/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBD;
import javax.swing.ImageIcon;

/**
 *
 * @author xavie
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta = new ConexaoBD(); //instanciação do objeto 

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conecta.conexao(); //método conexão
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBoasVindas = new javax.swing.JInternalFrame();
        jButtonMedico = new javax.swing.JButton();
        jButtonEnfermeira = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelInternalFrame = new javax.swing.JLabel();
        jLabelGerenciamento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItemEnfermeiro = new javax.swing.JMenuItem();
        jMenuItemPaciente = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBoasVindas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBoasVindas.setVisible(true);
        jInternalFrameBoasVindas.getContentPane().setLayout(null);

        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/médico.jpg"))); // NOI18N
        jButtonMedico.setToolTipText("Médicos");
        jButtonMedico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });
        jInternalFrameBoasVindas.getContentPane().add(jButtonMedico);
        jButtonMedico.setBounds(30, 90, 100, 100);

        jButtonEnfermeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enf.jpg"))); // NOI18N
        jButtonEnfermeira.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrameBoasVindas.getContentPane().add(jButtonEnfermeira);
        jButtonEnfermeira.setBounds(30, 210, 100, 100);

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pct.jpg"))); // NOI18N
        jButtonPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrameBoasVindas.getContentPane().add(jButtonPaciente);
        jButtonPaciente.setBounds(150, 90, 100, 100);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ag.png"))); // NOI18N
        jButtonAgenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrameBoasVindas.getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(150, 210, 100, 100);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jInternalFrameBoasVindas.getContentPane().add(jButtonSair);
        jButtonSair.setBounds(695, 10, 50, 50);
        jButtonSair.getAccessibleContext().setAccessibleName("");
        jButtonSair.getAccessibleContext().setAccessibleDescription("Sair da tela de Boas-Vindas");

        jLabelInternalFrame.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInternalFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInternalFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/painelfundo.jpg"))); // NOI18N
        jLabelInternalFrame.setText("jLabel2");
        jLabelInternalFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrameBoasVindas.getContentPane().add(jLabelInternalFrame);
        jLabelInternalFrame.setBounds(7, 64, 740, 300);

        jLabelGerenciamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelGerenciamento.setForeground(new java.awt.Color(0, 102, 204));
        jLabelGerenciamento.setText("Cadastro e Agenda");
        jInternalFrameBoasVindas.getContentPane().add(jLabelGerenciamento);
        jLabelGerenciamento.setBounds(10, 7, 202, 50);

        getContentPane().add(jInternalFrameBoasVindas);
        jInternalFrameBoasVindas.setBounds(15, 125, 770, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internalframe.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        jMenuCadastro.setText("Cadastro");

        jMenuItemMedico.setText("Médico");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemMedico);

        jMenuItemEnfermeiro.setText("Enfermeiro");
        jMenuItemEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnfermeiroActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemEnfermeiro);

        jMenuItemPaciente.setText("Paciente");
        jMenuCadastro.add(jMenuItemPaciente);

        jMenuItemUsuario.setText("Usuário");
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorio.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorio);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBoasVindas.setText("Tela de Boas-Vindas");
        jMenuItemTelaBoasVindas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBoasVindasActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBoasVindas);

        jMenuBar1.add(jMenuFerramentas);

        jMenu1.setText("Sair");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnfermeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEnfermeiroActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        jInternalFrameBoasVindas.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        conecta.desconexao();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemTelaBoasVindasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBoasVindasActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemTelaBoasVindasActionPerformed

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
        // TODO add your handling code here:
        /*ImageIcon icon = new ImageIcon("src/imagens/médico.png");
        icon.setImage(icon.getImage().getScaledInstance(jButtonMedico.getWidth(), jButtonMedico.getHeight(), 1));
        jButtonMedico.setIcon(icon);*/
        FormMedico telaFormMedico = new FormMedico();
        telaFormMedico.setVisible(true);
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
        // TODO add your handling code here:
        FormMedico telaFormMedico = new FormMedico();
        telaFormMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonEnfermeira;
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JInternalFrame jInternalFrameBoasVindas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGerenciamento;
    private javax.swing.JLabel jLabelInternalFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemEnfermeiro;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JMenuItem jMenuItemTelaBoasVindas;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuRelatorio;
    // End of variables declaration//GEN-END:variables
}
